server:
  port: 8769
management:
  metrics:
    web:
      server:
        #避免访问zipkin页面报java.lang.IllegalArgumentException
        auto-time-requests: false
spring:
  application:
    name: zipkin-server #不要使用下划线
sleuth:
  enabled: true
