server:
  port: 8002
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    api-user:
      path: /user/**
      serviceId: user-server
