server:
  port: 8001

spring:
  application:
    name: user-server
  zipkin:
    base-url: http://localhost:8769
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
